name : "action"


on: 
  push:
     branches: [ main ]
  
     

jobs:
   build:
      runs-on: ubuntu-lates
      steps:
          - name: checkout repository
            uses: action/checkout@v3
            
          - name: set up Docker buildx
            uses: docker/setup-buildx-action@v3
            
          - name: build Docker image
            run: docker build -t my-web-image:latest .
            
            
    
   
