name: "action"

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # Corrected typo here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Correct action name

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-web-image:latest .

      - name: Push image to Docker Hub
        run: docker push my-web-image:latest
