name : "action"


on: 
  push:
     branches: [ main ]
  
     

jobs:
   build:
      runs-on: ubuntu-lates
      steps:
          - name: checkout repository
            uses: action/checkout@v3
            
          - name: set up Docker buildx
            uses: docker/setup-buildx-action@v3
            with:
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}}
              
            
          - name: build Docker image
            run: docker build -t my-web-image:latest .
          - name: push image into docker hub
            run:  docker push my-web-image:latest 
            
            
    
   
